version: "3.0"

services:
  tunnel:
    image: vpnhouse/tunnel:v0.3.0
    container_name: tunnel
    restart: always
    ports:
      - 80:80
      - 443:443
      - 3000:3000/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/vpnhouse/tunnel:/opt/vpnhouse/tunnel/:rw
