# note: if you use 3.xx-incompatible version,
# please remove/update the version number below.
# Also, you may want to remove the "pull_policy"
# option due to compatibility issues.
version: "3.0"

services:
  tunnel:
    image: vpnhouse/tunnel:v0.2.7
    container_name: tunnel
    restart: always
    pull_policy: always
    ports:
      - 80:80
      - 443:443
      - 3000:3000/udp
    cap_add:
      - NET_ADMIN
    volumes:
      # TODO: CHANGE ME
      - /path/to/vpnhouse-data:/opt/vpnhouse/tunnel/:rw

