name: "on PR: run tests"

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run test fmt vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: do stuff
        env:
          CI: github
        run: make test fmt vet build/app
